apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prd-gtsk-uswest2-full-access
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prd-gtsk-uswest2-full-access-binding
subjects:
- kind: Group
  name: prd-gtsk-uswest2-full-access-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prd-gtsk-uswest2-full-access
  apiGroup: rbac.authorization.k8s.io