---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::257821106339:role/prd-gtsk-uswest1-core-alb-role


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-deployment-service-account
  namespace: prd-gtsk-uswest1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::257821106339:role/prd-gtsk-uswest1-core-secrets
