name = "frontend"
compatibility_date = "2022-01-20"
type = "webpack"
account_id = "91d7983e0bff08e0cf76f81cf79abe50"
route = "generaltask.com/*"
zone_id = "3902eeab1159d5dbc8604825e8b7c7b0"

[site]
bucket = "./build"
entry-point = "workers_site"
