export const _4 = '2px' // mini
export const _8 = '4px' // extra small
export const _12 = '6px' // small
export const _16 = '8px' // regular
export const _24 = '12px' // medium
export const _32 = '16px' // large
export const _64 = '32px' // extra large
export const _88 = '44px' // jumbo
export const _128 = '64px' // mammoth
