export const SET_TASKS = 'setTasks'
export const SET_TASKS_FETCH_STATUS = 'setTasksFetchStatus'
export const REMOVE_TASK = 'removeTask'
export const REMOVE_TASK_BY_ID = 'removeTaskById'
export const EXPAND_BODY = 'expandBody'
export const RETRACT_BODY = 'retractBody'
