name:                task-manager
version:             0.1.0.0
github:              "githubuser/task-manager"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/task-manager#readme>

# These extensions simply constitute a subset of what will eventually
# be conined "Haskell2021". For now, it's enough to know they
# constitute stable behavior.
default-extensions:
- RecordWildCards
- ConstraintKinds
- DeriveTraversable
- QuasiQuotes
- GeneralizedNewtypeDeriving
- ViewPatterns
- RankNTypes
- DerivingVia
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- TypeFamilies
- TypeOperators
- TypeApplications
- InstanceSigs

dependencies:
- base
- relude

library:
  source-dirs: src
  mixins:
  - base hiding (Prelude)
  - relude (Relude as Prelude)

executables:
  task-manager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - task-manager

tests:
  task-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - task-manager
