name: "Cloudflare Auto Deploy"
on:
  push:
    branches:
<<<<<<< HEAD
<<<<<<< HEAD
      - master
=======
      - main
>>>>>>> add master push and yarn
=======
      - master
>>>>>>> master
  workflow_dispatch:
    inputs:
      tags:
        description: "Manually deploy frontend to Cloudflare"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2.0.0

      - name: install dependencies
        run: "yarn install"

      - name install wrangler
        run: "yarn global add @cloudflare/wrangler"

      - name: build
        run: "yarn run build"

      - name: deploy using wrangler
        run: "wrangler publish"

        env:
          CF_EMAIL: ${{secrets.CF_EMAIL}}
          CF_API_KEY: ${{secrets.CF_API_KEY}}
