name: Cloudflare
on: 
  workflow_dispatch:
    inputs:
        tags:
          description: 'Deploy frontend to Cloudflare!'


jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2.0.0 

      - name: install dependencies
        run: 'npm install'

      - name: build
        run: 'npm run build'

      - name: deploy using wrangler 
        run: 'npx wrangler publish'
        
        env:
          CF_EMAIL: john@generaltask.io
          CF_API_KEY: 8238b2654916953b02d74abb1764b651258ca
