name: "Cloudflare Auto Deploy"
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: "Deploy frontend to Cloudflare"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2.0.0

      - name: install dependencies
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          yarn install

      - name: install wrangler
        run: "yarn global add @cloudflare/wrangler"

      - name: build
        run: "yarn build"

      - name: deploy using wrangler
        run: "wrangler publish"

        env:
          CF_EMAIL: ${{secrets.CF_EMAIL}}
          CF_API_KEY: ${{secrets.CF_API_KEY}}
